[project]
name = "custom-mem0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mem0ai>=0.1.113",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
]
